### ISSUE TITLE
1.16.0 breaks `pact:verify`

### ISSUE THREAD

**Issue by ojab** [pact-foundation/pact-support#81]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised
* [x] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **pact-support:** 1.16.0
* **pact-ruby-standalone** (if relevant): eg 2.3.1-1
* **OS**: e.g. Mac OSX 10.11.5

## Expected behaviour

It works!

## Actual behaviour

It fails with `NoMethodError: undefined method `configuration' for RSpec:Module`.

## Steps to reproduce

https://travis-ci.org/github/pact-foundation/pact-ruby/jobs/741293133#L416

**Comment by jmortlock** [comment]
I can also confirm this as a problem after updating to v1.16 today.

Rolling back to 1.15 fixes the problem

**Comment by panasyuk** [comment]
Some observations:
1.15.1 – worked good.
1.15.2 - 1.16.x – show the error.

### The error

`NoMethodError - undefined method 'params_hash_type?' for Pact::Query:Class`

<details>
<summary>Backtrace</summary>

```
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-support-1.15.2/lib/pact/consumer_contract/query.rb:101:in `normalize_params'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-support-1.15.2/lib/pact/consumer_contract/query.rb:62:in `block in parse_nested_query'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-support-1.15.2/lib/pact/consumer_contract/query.rb:59:in `each'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-support-1.15.2/lib/pact/consumer_contract/query.rb:59:in `parse_nested_query'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-support-1.15.2/lib/pact/consumer_contract/query.rb:22:in `parse_string'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-support-1.15.2/lib/pact/consumer_contract/interaction_v2_parser.rb:28:in `parse_request'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-support-1.15.2/lib/pact/consumer_contract/interaction_v2_parser.rb:15:in `call'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-support-1.15.2/lib/pact/consumer_contract/interaction_parser.rb:16:in `parse_v2_interaction'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-support-1.15.2/lib/pact/consumer_contract/interaction_parser.rb:10:in `call'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-support-1.15.2/lib/pact/consumer_contract/interaction.rb:22:in `from_hash'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-mock_service-3.6.2/lib/pact/mock_service/request_handlers/interaction_post.rb:26:in `respond'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-mock_service-3.6.2/lib/pact/mock_service/request_handlers/base_request_handler.rb:17:in `call'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/cascade.rb:47:in `block in call'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/cascade.rb:38:in `each'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/cascade.rb:38:in `call'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-mock_service-3.6.2/lib/pact/consumer/mock_service/cors_origin_header_middleware.rb:11:in `call'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-mock_service-3.6.2/lib/pact/consumer/mock_service/error_handler.rb:13:in `call'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-mock_service-3.6.2/lib/pact/mock_service/app.rb:34:in `call'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/pact-mock_service-3.6.2/lib/pact/consumer/server.rb:22:in `call'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/webrick-1.6.1/lib/webrick/httpserver.rb:140:in `service'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/webrick-1.6.1/lib/webrick/httpserver.rb:96:in `run'
/Users/panasyuk/.rvm/gems/ruby-2.6.5/gems/webrick-1.6.1/lib/webrick/server.rb:307:in `block in start_thread'
```
</details>

<details>
<summary>Gemfile.lock</summary>

```
    pact (1.55.5)
      pact-mock_service (~> 3.0, >= 3.3.1)
      pact-support (~> 1.15)
      rack-test (>= 0.6.3, < 2.0.0)
      rspec (~> 3.0)
      term-ansicolor (~> 1.0)
      thor (>= 0.20, < 2.0)
      webrick (~> 1.3)
    pact-mock_service (3.6.2)
      filelock (~> 1.1)
      find_a_port (~> 1.0.1)
      json
      pact-support (~> 1.12, >= 1.12.0)
      rack (~> 2.0)
      rspec (>= 2.14)
      term-ansicolor (~> 1.0)
      thor (>= 0.19, < 2.0)
      webrick (~> 1.3)
    pact-support (1.15.2)
      awesome_print (~> 1.1)
      diff-lcs (~> 1.4)
      randexp (~> 0.1.7)
      rspec (>= 2.14)
      term-ansicolor (~> 1.0)
```
</details>

**Comment by bethesque** [comment]
Upgrade to 1.55.6 of the pact gem (the fix is there, not pact-support) @ojab.

@panasyuk your issue is different. Please upgrade to 1.16.1 of pact-support.
